---
- hosts: all
  gather_facts: no
  vars:
    hotfix: false
    PACKAGE_PATH: /tmp
  tasks:
    - shell: echo {{packname}} | grep -e gameserver -e loginserver
      register: check_server_result
      ignore_errors: True

    - name: copy...
      copy:
          src: "{{PACKAGE_PATH}}/{{packname}}"
          dest: "{{PACKAGE_PATH}}/{{packname}}"
          mode: 0644

    - name: try create {{ggApp_workspace}}
      command: mkdir -p {{ggApp_workspace}}
      args:
          creates: "{{ggApp_workspace}}"


    - name: unarchive non server
      shell: tar -izxvf {{PACKAGE_PATH}}/{{packname}} -C {{ggApp_workspace}}
      when: check_server_result.rc != 0

    - name: unarchive server
      shell: mkdir -p {{ggApp_workspace}}/{{inventory_hostname}} && tar --strip-components=1 -izxvf {{PACKAGE_PATH}}/{{packname}} -C {{ggApp_workspace}}/{{inventory_hostname}}
      when: check_server_result.rc == 0

    - name: hotfix...
      shell: "tar -itf {{PACKAGE_PATH}}/{{packname}} | xargs sh gm.sh 0 hotfix"
      args:
          chdir: "{{ggApp_workspace}}/{{inventory_hostname}}/shell"
      when: hotfix
